import { afterEach, describe, expect, it, vi } from 'vitest'
import { createViewerRuntime, getViewerApi, type ViewerRuntime, type Molecule } from './runtime'
import { newAtom } from './core'
import { getViewerRuntimeServices } from '../runtime/ViewerRuntime'
import { useMoleculeStore } from './state'

const runtimes: ViewerRuntime[] = []
function instance() {
  const runtime = createViewerRuntime()
  runtimes.push(runtime)
  return { runtime, api: getViewerApi(runtime) }
}
function molecule(): Molecule {
  const a = newAtom('C', 0, 0, 0)
  const b = newAtom('O', 1.4, 0, 0)
  return { atoms: [a, b], bonds: [{ id: 'co', atomId1: a.id, atomId2: b.id, order: 1 }] }
}
afterEach(() => { runtimes.splice(0).forEach(runtime => runtime.dispose()) })

describe('instance-bound public viewer API', () => {
  it('isolates two editable instances and the default store, including selection and history', () => {
    const left = instance()
    const right = instance()
    const defaultState = useMoleculeStore.getState()
    const original = molecule()
    left.api.setMolecule(original)
    right.api.setMolecule(original)
    left.api.history.clear()
    right.api.history.clear()
    const rightBefore = right.api.getSnapshot()
    const atomId = original.atoms[0].id
    left.api.selection.set([atomId, 'missing'])
    left.api.edit.replaceAtom(atomId, 'N')
    expect(left.api.getSnapshot().selectedAtomIds).toEqual([atomId])
    expect(left.api.getSnapshot().molecule.atoms[0].symbol).toBe('N')
    expect(left.api.getSnapshot().history.undoCount).toBe(1)
    expect(right.api.getSnapshot()).toBe(rightBefore)
    expect(useMoleculeStore.getState()).toBe(defaultState)
    left.api.history.undo()
    expect(left.api.getSnapshot().molecule).toEqual(original)
    left.api.history.redo()
    expect(left.api.getSnapshot().molecule.atoms[0].symbol).toBe('N')
    right.api.edit.moveAtom(atomId, 4, 5, 6)
    expect(left.api.getSnapshot().molecule.atoms[0].x).toBe(0)
    expect(right.api.getSnapshot().history.undoCount).toBe(1)
    expect(getViewerApi(left.runtime)).toBe(left.api)
  })

  it('coalesces UI/store changes into a complete snapshot and reports history-only changes', async () => {
    const { runtime, api } = instance()
    api.setMolecule(molecule())
    api.history.clear()
    const initial = api.getSnapshot()
    const listener = vi.fn(() => api.getSnapshot())
    api.subscribe(listener)
    // Same path as a viewer gesture, without going through the public facade.
    const store = getViewerRuntimeServices(runtime).moleculeStore
    store.getState().moveAtom(initial.molecule.atoms[0].id, 2, 3, 4)
    expect(listener).not.toHaveBeenCalled()
    await Promise.resolve()
    expect(listener).toHaveBeenCalledTimes(1)
    const current = listener.mock.results[0].value
    expect(current.molecule.atoms[0].x).toBe(2)
    expect(current.history).toEqual({ canUndo: true, canRedo: false, undoCount: 1, redoCount: 0 })
    expect(api.getSnapshot()).toBe(current)
    api.history.clear()
    await Promise.resolve()
    expect(listener).toHaveBeenCalledTimes(2)
    expect(api.getSnapshot().molecule).toBe(current.molecule)
    expect(api.getSnapshot().history.canUndo).toBe(false)
  })

  it('keeps rejected edits and repeated selection out of history and notifications', async () => {
    const { api } = instance()
    api.setMolecule(molecule())
    api.history.clear()
    const initial = api.getSnapshot()
    const listener = vi.fn()
    api.subscribe(listener)
    expect(api.edit.setChirality(initial.molecule.atoms[0].id, 'R').ok).toBe(false)
    expect(api.edit.setBondLength('missing', 'also-missing', 1.2).ok).toBe(false)
    await Promise.resolve()
    expect(api.getSnapshot()).toBe(initial)
    expect(listener).not.toHaveBeenCalled()
    api.selection.set([initial.molecule.atoms[0].id], ['co'])
    await Promise.resolve()
    expect(listener).toHaveBeenCalledTimes(1)
    const selected = api.getSnapshot()
    api.selection.set(selected.selectedAtomIds, selected.selectedBondIds)
    await Promise.resolve()
    expect(api.getSnapshot()).toBe(selected)
    expect(listener).toHaveBeenCalledTimes(1)
    expect(api.getSnapshot().history.undoCount).toBe(0)
    expect(Object.isFrozen(selected.selectedAtomIds)).toBe(true)
  })

  it('prunes selection on deletion and restores structure in one undo', () => {
    const { api } = instance()
    const original = molecule()
    api.setMolecule(original)
    api.history.clear()
    api.selection.set([original.atoms[1].id], ['co'])
    api.edit.removeSelected()
    expect(api.getSnapshot().molecule.atoms).toHaveLength(1)
    expect(api.getSnapshot().selectedAtomIds).toEqual([])
    expect(api.getSnapshot().selectedBondIds).toEqual([])
    expect(api.getSnapshot().history.undoCount).toBe(1)
    api.history.undo()
    expect(api.getSnapshot().molecule).toEqual(original)
    expect(api.getSnapshot().selectedAtomIds).toEqual([])
  })

  it('does not allow public history calls to corrupt an active gesture', () => {
    const { runtime, api } = instance()
    api.setMolecule(molecule())
    const state = getViewerRuntimeServices(runtime).moleculeStore.getState()
    const transaction = state.beginTransaction('test-gesture')
    expect(api.getSnapshot().history.canUndo).toBe(false)
    expect(() => api.history.clear()).toThrow(/active edit/)
    expect(() => api.history.undo()).toThrow(/active edit/)
    expect(() => api.history.redo()).toThrow(/active edit/)
    transaction.cancel()
    expect(api.getSnapshot().history.canUndo).toBe(true)
  })

  it('routes camera, capture and display controls only to their runtime', async () => {
    const left = instance()
    const right = instance()
    const fit = vi.fn()
    const reset = vi.fn()
    const focus = vi.fn()
    const axes = vi.fn()
    const grid = vi.fn()
    const services = getViewerRuntimeServices(left.runtime)
    const unregister = services.viewport.register({
      fitViewport: fit, resetViewport: reset, focusViewportSelection: focus,
      setViewportAxesVisible: axes, setViewportGridVisible: grid,
    })
    services.capture.register(() => 'data:image/png;base64,test')
    expect(left.api.view.fit()).toBe(true)
    expect(right.api.view.fit()).toBe(false)
    left.api.view.reset()
    left.api.view.focusSelection()
    left.api.view.setAxesVisible(true)
    left.api.view.setGridVisible(false)
    expect(fit).toHaveBeenCalledTimes(1)
    expect(reset).toHaveBeenCalledTimes(1)
    expect(focus).toHaveBeenCalledTimes(1)
    expect(axes).toHaveBeenCalledWith(true)
    expect(grid).toHaveBeenCalledWith(false)
    expect(left.api.view.captureImage()).toContain('data:image/png')
    expect(right.api.view.captureImage()).toBeNull()
    const listener = vi.fn()
    left.api.subscribe(listener)
    left.api.view.setDisplayMode('stick')
    left.api.view.setShowAtomLabels(true)
    left.api.view.setTheme('iboview')
    await Promise.resolve()
    expect(listener).toHaveBeenCalledTimes(1)
    expect(left.api.getSnapshot()).toMatchObject({ displayMode: 'stick', showAtomLabels: true, themeId: 'iboview' })
    expect(right.api.getSnapshot()).toMatchObject({ displayMode: 'ball-stick', showAtomLabels: false, themeId: 'default' })
    expect(left.api.getSnapshot().history.undoCount).toBe(0)
    unregister()
    expect(left.api.view.fit()).toBe(false)
  })

  it('cancels pending callbacks on unsubscribe/dispose and rejects stale handles', async () => {
    const { runtime, api } = instance()
    const store = getViewerRuntimeServices(runtime).moleculeStore
    const listener = vi.fn()
    const stop = api.subscribe(listener)
    api.setMolecule(molecule())
    stop()
    stop()
    await Promise.resolve()
    expect(listener).not.toHaveBeenCalled()
    api.subscribe(listener)
    api.selection.set([api.getSnapshot().molecule.atoms[0].id])
    runtime.dispose()
    runtime.dispose()
    await Promise.resolve()
    store.getState().setMolecule(molecule())
    await Promise.resolve()
    expect(listener).not.toHaveBeenCalled()
    expect(() => api.getSnapshot()).toThrow(/disposed/)
    expect(() => api.setMolecule(molecule())).toThrow(/disposed/)
    expect(() => api.edit.removeSelected()).toThrow(/disposed/)
    expect(() => api.selection.clear()).toThrow(/disposed/)
    expect(() => api.history.undo()).toThrow(/disposed/)
    expect(() => api.view.fit()).toThrow(/disposed/)
    expect(() => api.subscribe(listener)).toThrow(/disposed/)
    expect(() => getViewerApi(runtime)).toThrow(/disposed/)
  })
})
