import { AG_COORDINATION_SET } from './ag'
import { AU_COORDINATION_SET } from './au'
import { BH_COORDINATION_SET } from './bh'
import { CD_COORDINATION_SET } from './cd'
import { CN_COORDINATION_SET } from './cn'
import { CO_COORDINATION_SET } from './co'
import { CR_COORDINATION_SET } from './cr'
import { CU_COORDINATION_SET } from './cu'
import { DB_COORDINATION_SET } from './db'
import { DS_COORDINATION_SET } from './ds'
import { FE_COORDINATION_SET } from './fe'
import { HF_COORDINATION_SET } from './hf'
import { HG_COORDINATION_SET } from './hg'
import { HS_COORDINATION_SET } from './hs'
import { IR_COORDINATION_SET } from './ir'
import { MN_COORDINATION_SET } from './mn'
import { MO_COORDINATION_SET } from './mo'
import { MT_COORDINATION_SET } from './mt'
import { NB_COORDINATION_SET } from './nb'
import { NI_COORDINATION_SET } from './ni'
import { OS_COORDINATION_SET } from './os'
import { PD_COORDINATION_SET } from './pd'
import { PT_COORDINATION_SET } from './pt'
import { RE_COORDINATION_SET } from './re'
import { RF_COORDINATION_SET } from './rf'
import { RG_COORDINATION_SET } from './rg'
import { RH_COORDINATION_SET } from './rh'
import { RU_COORDINATION_SET } from './ru'
import { SC_COORDINATION_SET } from './sc'
import { SG_COORDINATION_SET } from './sg'
import { TA_COORDINATION_SET } from './ta'
import { TC_COORDINATION_SET } from './tc'
import { TI_COORDINATION_SET } from './ti'
import { V_COORDINATION_SET } from './v'
import { W_COORDINATION_SET } from './w'
import { Y_COORDINATION_SET } from './y'
import { ZN_COORDINATION_SET } from './zn'
import { ZR_COORDINATION_SET } from './zr'

export const TRANSITION_METAL_COORDINATION_SETS = [
  SC_COORDINATION_SET, TI_COORDINATION_SET, V_COORDINATION_SET, CR_COORDINATION_SET,
  MN_COORDINATION_SET, FE_COORDINATION_SET, CO_COORDINATION_SET, NI_COORDINATION_SET,
  CU_COORDINATION_SET, ZN_COORDINATION_SET,
  Y_COORDINATION_SET, ZR_COORDINATION_SET, NB_COORDINATION_SET, MO_COORDINATION_SET,
  TC_COORDINATION_SET, RU_COORDINATION_SET, RH_COORDINATION_SET, PD_COORDINATION_SET,
  AG_COORDINATION_SET, CD_COORDINATION_SET,
  HF_COORDINATION_SET, TA_COORDINATION_SET, W_COORDINATION_SET, RE_COORDINATION_SET,
  OS_COORDINATION_SET, IR_COORDINATION_SET, PT_COORDINATION_SET, AU_COORDINATION_SET,
  HG_COORDINATION_SET,
  RF_COORDINATION_SET, DB_COORDINATION_SET, SG_COORDINATION_SET, BH_COORDINATION_SET,
  HS_COORDINATION_SET, MT_COORDINATION_SET, DS_COORDINATION_SET, RG_COORDINATION_SET,
  CN_COORDINATION_SET,
] as const

export {
  AG_COORDINATION_SET, AU_COORDINATION_SET, BH_COORDINATION_SET, CD_COORDINATION_SET,
  CN_COORDINATION_SET, CO_COORDINATION_SET, CR_COORDINATION_SET, CU_COORDINATION_SET,
  DB_COORDINATION_SET, DS_COORDINATION_SET, FE_COORDINATION_SET, HF_COORDINATION_SET,
  HG_COORDINATION_SET, HS_COORDINATION_SET, IR_COORDINATION_SET, MN_COORDINATION_SET,
  MO_COORDINATION_SET, MT_COORDINATION_SET, NB_COORDINATION_SET, NI_COORDINATION_SET,
  OS_COORDINATION_SET, PD_COORDINATION_SET, PT_COORDINATION_SET, RE_COORDINATION_SET,
  RF_COORDINATION_SET, RG_COORDINATION_SET, RH_COORDINATION_SET, RU_COORDINATION_SET,
  SC_COORDINATION_SET, SG_COORDINATION_SET, TA_COORDINATION_SET, TC_COORDINATION_SET,
  TI_COORDINATION_SET, V_COORDINATION_SET, W_COORDINATION_SET, Y_COORDINATION_SET,
  ZN_COORDINATION_SET, ZR_COORDINATION_SET,
}
